definitions:
  cms.Datapoint:
    properties:
      Average:
        type: number
      Maximum:
        type: number
      Minimum:
        type: number
      instanceId:
        type: string
      timestamp:
        type: integer
      userId:
        type: string
    type: object
  controllers.AclListReq:
    properties:
      acl_id:
        type: string
      comment:
        type: string
      host:
        items:
          type: string
        type: array
      ip:
        items:
          type: string
        type: array
    required:
    - acl_id
    type: object
  controllers.RefreshCdnReq:
    properties:
      urls:
        description: 主机名,支持通配符
        items:
          type: string
        type: array
    required:
    - urls
    type: object
  controllers.getDataPointReq:
    properties:
      hostName:
        description: 主机名,支持通配符
        example:
        - sdcf_v3_030
        items:
          type: string
        type: array
      instanceId:
        description: 主机Id
        example:
        - i-bp1d1oh9a06r70buf03l
        items:
          type: string
        type: array
    type: object
  controllers.searchHostReq:
    properties:
      hostname:
        description: 主机名,支持通配符
        type: string
      ip:
        description: 主机名,支持通配符
        type: string
    type: object
  controllers.setEcsWeight:
    properties:
      hostname:
        description: 主机名,支持通配符
        type: string
      weight:
        description: 权重  *int 防止0在json的时候被丢掉
        maximum: 100
        minimum: 0
        type: integer
    required:
    - hostname
    - weight
    type: object
  utils.ApiJson:
    properties:
      data: {}
      msg:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/cdn/refresh:
    post:
      consumes:
      - application/json
      description: 根据提供的URL去刷新CDN
      parameters:
      - description: urls 是 []string
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/controllers.RefreshCdnReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ApiJson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ApiJson'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ApiJson'
      summary: 刷新CDN
      tags:
      - cdn
  /api/cms/ecs/cpu:
    post:
      consumes:
      - application/json
      description: 根据ECS  获取CPU使用率
      parameters:
      - description: hostName 是 []string
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/controllers.getDataPointReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.ApiJson'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/cms.Datapoint'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ApiJson'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ApiJson'
      summary: 获取ECS CPU信息
      tags:
      - 监控CMS
  /api/ecs/refresh:
    post:
      consumes:
      - application/json
      description: 刷新ecs实例列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ApiJson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ApiJson'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ApiJson'
      summary: 刷新ecs实例列表
      tags:
      - ecs
  /api/ecs/search:
    post:
      consumes:
      - application/json
      description: 会设置服务器 所有负载均衡里的权重
      parameters:
      - description: 'hostname 必填 ；weight 为 0-100之间的数字 必填 '
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/controllers.setEcsWeight'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ApiJson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ApiJson'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ApiJson'
      summary: 设置所有包含该服务器的负载均衡里的权重
      tags:
      - ecs
  /api/slb/acl/add:
    post:
      consumes:
      - application/json
      description: 添加主机到ACL
      parameters:
      - description: acl_id 是 slb accessList的ID ； host 和 ip不能同时为空 ，类型均为 []string
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/controllers.AclListReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ApiJson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ApiJson'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ApiJson'
      summary: 添加主机到ACL
      tags:
      - slb
  /api/slb/acl/delete:
    post:
      consumes:
      - application/json
      description: 从ACL移除主机
      parameters:
      - description: acl_id 是 slb accessList的ID ； host 和 ip不能同时为空 ，类型均为 []string
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/controllers.AclListReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ApiJson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ApiJson'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ApiJson'
      summary: 从ACL移除主机
      tags:
      - slb
swagger: "2.0"
